apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: app
          image: ghcr.io/yagorx/go-service-ci:96d62c4a29fa75f80da5f031de38c2d1c2e664ba
          imagePullPolicy: Always
          ports:
            - containerPort: 10080
