name: Go CI

permissions:
  contents: read
  packages: write
  
on:
  push:
    branches: [ "master", "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:
    inputs:
      run_e2e:
        description: "Run e2e tests"
        required: true
        type: boolean
        default: true

jobs:
  lint:
    name: Lint (golangci-lint v2)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      - name: Install golangci-lint v2
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b /usr/local/bin v2.0.1

      - name: Check golangci-lint version
        run: golangci-lint version

      - name: Verify config
        run: golangci-lint config verify

      - name: Run golangci-lint
        run: golangci-lint run

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      - name: Run unit tests with coverage
        run: make unit-test

  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      # ⚠️ Docker нужен для docker-compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run integration tests
        run: make test-integration

  e2e-test:
    name: E2E tests (manual)
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_e2e }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run e2e tests
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          IMAGE_TAG: ${{ github.sha }}
        run: make test-e2e-docker

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      - name: Build application
        run: make build
    
  login_push:
    name: LoginAndPush
    runs-on: ubuntu-latest
    needs: [build, security, integration-test, unit-test, lint]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      env:
          GITHUB_USER: ${{ github.repository_owner }}
          IMAGE_TAG: ${{ github.sha }}
      run: |
        make docker-build
        make docker-push
